import type { Metadata } from "next";
import "@/app/globals.css";
import UserLayout from "../../../components/navbars/user";

export const metadata: Metadata = {
  title: "User App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <UserLayout>
        {children}

      </UserLayout>
    </>
  )
}
